language: python
python:
- "3.6.3"
install:
- pip3 install django
- pip3 install djangorestframework
- pip3 install coverage
- pip3 install requests
- pip3 install django-cors-headers
- pip3 install django-rest-auth
- pip3 install django-allauth
script:
- cd Classtagram/backend
- python3 manage.py test
