language: python
python:
	- "3.6"
branches:
	- master
	- develop
before_script:
	- cd Classtagram/backend
install:
	- pip install django
	- pip install djangorestframework
	- pip install coverage
	- pip install requests
	- pip install django-cors-headers
	- pip install django-rest-auth
	- pip install django-allauth
script:
	- coverage run --source='.' manage.py test
	- coverage report
